### ISSUE TITLE
能否把cups编译进去呢

### ISSUE THREAD

**Issue by qxwo** [xydche/onecloud-openwrt#4]
自己试了echo "src-git cups https://github.com/apple/cups.git" >> feeds.conf.default 加进去，好像没啥用
求方法，谢谢
呃，没注意看说明是macos的。。。。

**Comment by xydche** [comment]
试试docker

**Comment by dj56959566** [comment]
> 试试docker 请问玩客云docker默认装目录和别的架构不一样吗。怎么增加daemon.json文件进去。就无法联接到docker上。也就是在换镜像源这里就出问题找了好多资料修改重启都无效呀。
能没有下次编一个把玩客云和docker 未用完的空间全扩给他们二个呀。对于不懂docker的小白。很难搞呀

**Comment by xydche** [comment]
> > 试试docker 请问玩客云docker默认装目录和别的架构不一样吗。怎么增加daemon.json文件进去。就无法联接到docker上。也就是在换镜像源这里就出问题找了好多资料修改重启都无效呀。
> > 能没有下次编一个把玩客云和docker 未用完的空间全扩给他们二个呀。对于不懂docker的小白。很难搞呀

建议fork后自定义配置
