### ISSUE TITLE
2024.10.21-1119进不了后台

### ISSUE THREAD

**Issue by dj56959566** [xydche/onecloud-openwrt#5]
刷进去好像IP不对。进不了后台。刷了二次了。

**Comment by xydche** [comment]
最近lede那有大动作，等有空了把配置重新搓一边

**Comment by dj56959566** [comment]
登录ip: 192.168.10.99  网关192.168.10.1？？？？乍进不去呢。能没能编的时候把docker编进去。进一步把docker源也换国内源呀。谢谢

**Comment by dj56959566** [comment]
扩容：系统和docker

wget -U "" -O expand-root.sh "https://openwrt.org/_export/code/docs/guide-user/advanced/expand_root?codeblock=0"
chmod +x expand-root.sh
./expand-root.sh

**Comment by dj56959566** [comment]
你好我克隆你的改编工作流跑不完呢。

**Comment by xydche** [comment]
> 你好我克隆你的改编工作流跑不完呢。

检查配置，我这正常

**Comment by dj56959566** [comment]
你是说的那些配置……

**Comment by xydche** [comment]
> > 你好我克隆你的改编工作流跑不完呢。
> 
> 检查配置，我这正常

查看日志看是卡在哪里了，一点一点排查。
