### ISSUE TITLE
2024.12.23-1144 固件解析失败

### ISSUE THREAD

**Issue by wangdashuaige** [xydche/onecloud-openwrt#7]
解析烧录固件失败
![解析失败](https://github.com/user-attachments/assets/005e81e5-eb99-400d-bb0f-37bfe32191c5)

**Comment by wangdashuaige** [comment]
[openwrt-amlogic-meson8b-thunder-onecloud-ext4-emmc.img.gz](https://github.com/xydche/onecloud-openwrt/releases/download/2024.12.23-1144/openwrt-amlogic-meson8b-thunder-onecloud-ext4-emmc.img.gz)

**Comment by xydche** [comment]
是下载的名字带burn的包吗？
